name: expedient
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.6.0
  redux_persist_flutter: ^0.8.2
  cupertino_icons: ^0.1.3
  bezier_chart: ^1.0.17+1
  flutter_phoenix: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf